app_blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('<int:post_id>/', views.post, name='post'),
    path('exemplo/', views.exemplo, name='exemplo')
]

app_home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='home')
]

projeto/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_home.urls')),
    path('blog/', include('app_blog.urls')),
]

app_blog/models.py
from django.db import models

# Create your models here.

app_home/models.py
from django.db import models

# Create your models here.

app_blog/views.py
from django.http import Http404
from django.shortcuts import render

from app_blog.data import posts


# Create your views here.
def blog(request):

    context = {
        'text': 'Página do BLOG - 2',
        'title': 'Blog',
        'posts': posts
    }

    return render(request, 'global/blog.html', context)

def post(request, post_id):
    found_post = None

    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break

    if found_post is None:
        raise Http404('Post não existe.')
    
    context = {
        'text': 'Página do BLOG - 2',
        'title': 'Posts',
        'post': found_post
    }
    return render(request, 'global/post.html', context)

def exemplo(request):

    context = {
        'text': 'Página do EXEMPLO - 2',
        'title': 'Exemplo'
    }

    return render(request, 'global/exemplo.html', context)

app_home/views.py
from django.shortcuts import render


# Create your views here.
def index(request):

    context = {
        # 'text': 'Inicial',
        'title': 'Home'
    }

    return render(request, 'app_home/index.html', context)

app_blog/templates/global/blog.html
{% extends "global/base.html" %}

{% block titulo %}{{text}}{% endblock titulo %}

{% block post %}
    {% for post in posts %}
        {% include "global/partials/postblock.html" %}
    {% endfor %}
{% endblock post %}

app_blog/templates/global/exemplo.html
{% extends "global/base.html" %}

{% block titulo %}{{text}}{% endblock titulo %}

app_blog/templates/global/post.html
{% extends "global/base.html" %}

{% block title %}{{title}}{% endblock title %}

{% block post %}

    <article class="post single-post">
        <header>
            <h2 class="post__title">
                <a href="{% url 'blog:post' post.id %}">
                    {{post.title}}
                </a>
            </h2>
        </header>
        <div class="post__body">
            {{post.body}}
        </div>
    </article>

{% endblock post %}

app_home/templates/app_home/index.html
{% extends "global/base.html" %}

{% block titulo %}{{text}}{% endblock titulo %}

{% block home %}
    <h1>HOME</h1>
{% endblock home %}